---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
collections: 
upload_dir: images/forestryio
public_path: "{{ site.baseurl }}/forestryio/images"
front_matter_path: "/images/forestryio"
use_front_matter_path: true
file_template: ":filename:"
